name: Tests 🛠️
on: [push]
jobs:
  applications-test-units:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        check-latest: true
    - run : echo "🎉"