apiVersion: v1
kind: ConfigMap
metadata:
  name: go-proxy-config
data:
  goproxy.yaml: |
    apiVersion: 1
    proxies:
    - namespace: example.org
      entries:
        repo: https://github.com/user/repo.git